// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQcj2ClI1I76GeMaZM2K_I24CNtnjixeU',
    appId: '1:641295667860:web:11ab0d2da56a8afc1b9a81',
    messagingSenderId: '641295667860',
    projectId: 'expensixfinal',
    authDomain: 'expensixfinal.firebaseapp.com',
    storageBucket: 'expensixfinal.firebasestorage.app',
    measurementId: 'G-9JVP61Q765',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBva4CjN-QNCiZas_edxjLxXD3OJss_NBM',
    appId: '1:641295667860:android:721b2512efde4a361b9a81',
    messagingSenderId: '641295667860',
    projectId: 'expensixfinal',
    storageBucket: 'expensixfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZ7XpaES2QoGU03ewuelSRzJiNQ-TCQc',
    appId: '1:641295667860:ios:07fb8833476d4edf1b9a81',
    messagingSenderId: '641295667860',
    projectId: 'expensixfinal',
    storageBucket: 'expensixfinal.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZ7XpaES2QoGU03ewuelSRzJiNQ-TCQc',
    appId: '1:641295667860:ios:07fb8833476d4edf1b9a81',
    messagingSenderId: '641295667860',
    projectId: 'expensixfinal',
    storageBucket: 'expensixfinal.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
